---
- name: ensure latest ssh-client is installed
  become: true
  package: name=openssh-client state=latest

- name: install ssh-server
  become: true
  package: name=openssh-server state=latest

- name: disable password access
  become: true
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root
  register: result

- name: restart ssh server after setting config
  become: true
  when: result.changed
  service: name=ssh state=restarted enabled=yes
