---
# # 1. Add the Spotify repository signing key to be able to verify downloaded packages
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886

# # 2. Add the Spotify repository
# echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list

# # 3. Update list of available packages
# sudo apt-get update

# # 4. Install Spotify
# sudo apt-get install spotify-client

# - name: add google apt key
#   become: true
#   apt_key: url=https://dl.google.com/linux/linux_signing_key.pub state=present

# - name: add google apt repo
#   become: true
#   apt_repository: repo="deb {{ item }}" state=present
#   with_items:
#     - "http://dl.google.com/linux/chrome/deb/ stable main"

- name: install applications
  become: true
  package: name={{ item }} state=latest
  with_items:
    # - google-chrome-stable
    - tmux
    - chromium-browser
    - htop
    - smartmontools
    - tlp

- name: ensure power saving tools are enabled
  become: true
  systemd: name={{ item }}.service state=started daemon_reload=yes enabled=yes
  with_items:
    - tlp
    - tlp-sleep

- name: ensure conflicting power saving package is disabled
  become: true
  systemd: name="systemd-rfkill.service" enabled=no state=stopped

- name: download terraform package
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /var/tmp/terraform-{{ terraform_version }}.zip
    checksum: "sha256:{{ terraform_shasum }}"

- name: unzip terraform package
  unarchive:
    src: "/var/tmp/terraform-{{ terraform_version }}.zip"
    dest: "/var/tmp/"

- name: add terraform binary to path
  become: true
  copy:
    src: /var/tmp/terraform
    dest: /usr/local/bin/terraform
    mode: 0755

- name: download terragrunt package
  get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64"
    dest: /var/tmp/terraform-{{ terragrunt_version }}
    checksum: "sha256:{{ terragrunt_shasum }}"

- name: add terragrunt binary to path
  become: true
  copy:
    src: /var/tmp/terraform-{{ terragrunt_version }}
    dest: /usr/local/bin/terragrunt
    mode: 0755

- name: install current google GPG key
  become: true
  apt_key: state=present url=https://packages.cloud.google.com/apt/doc/apt-key.gpg id=6A030B21BA07F4FB

- name: add google apt repo
  become: true
  apt_repository:
    repo: "deb https://packages.cloud.google.com/apt cloud-sdk-bionic main"
    state: present

- name: install google-cloud-sdk
  become: true
  apt:
    name: "google-cloud-sdk"
    state: present
    update_cache: true

- name: download helm tarball
  become: true
  get_url:
    url: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: /var/tmp/helm-{{ helm_version }}.tar.gz
    checksum: "sha256:{{ helm_shasum }}"

- name: untar helm
  become: true
  unarchive:
    src: "/var/tmp/helm-{{ helm_version }}.tar.gz"
    dest: "/var/tmp/"

- name: add helm binary to path
  become: true
  copy:
    src: /var/tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: 0755
