---
# # 1. Add the Spotify repository signing key to be able to verify downloaded packages
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886

# # 2. Add the Spotify repository
# echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list

# # 3. Update list of available packages
# sudo apt-get update

# # 4. Install Spotify
# sudo apt-get install spotify-client

# - name: add google apt key
#   become: true
#   apt_key: url=https://dl.google.com/linux/linux_signing_key.pub state=present

# - name: add google apt repo
#   become: true
#   apt_repository: repo="deb {{ item }}" state=present
#   with_items:
#     - "http://dl.google.com/linux/chrome/deb/ stable main"

- name: install applications
  become: true
  package: name={{ item }} state=latest
  with_items:
    # - google-chrome-stable
    - tmux
    - chromium-browser
    - htop
    - smartmontools
    - tlp

- name: ensure power saving tools are enabled
  become: true
  systemd: name={{ item }}.service state=started daemon_reload=yes enabled=yes
  with_items:
    - tlp
    - tlp-sleep

- name: ensure conflicting power saving package is disabled
  become: true
  systemd: name="systemd-rfkill.service" enabled=no state=stopped
