---
- name: add spotify apt key
  become: true
  apt_key: url=https://download.spotify.com/debian/pubkey.gpg state=present

- name: add spotify apt repo
  become: true
  apt_repository: repo="deb {{ item }}" state=present
  with_items:
    - "http://repository.spotify.com stable non-free"

- name: what's ma distro?
  shell: lsb_release -c | awk '{print $2}'
  register: ubuntu_version

- name: install applications
  become: true
  package: name={{ item }} state=latest
  with_items:
    - tmux
    - spotify-client
    - chromium-browser
    - htop

# - name: download terraform package
#   get_url:
#     url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
#     dest: /var/tmp/terraform-{{ terraform_version }}.zip
#     checksum: "sha256:{{ terraform_shasum }}"

# - name: unzip terraform package
#   unarchive:
#     src: "/var/tmp/terraform-{{ terraform_version }}.zip"
#     dest: "/var/tmp/"

# - name: add terraform binary to path
#   become: true
#   copy:
#     src: /var/tmp/terraform
#     dest: /usr/local/bin/terraform
#     mode: 0755

# - name: download terragrunt package
#   get_url:
#     url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64"
#     dest: /var/tmp/terraform-{{ terragrunt_version }}
#     checksum: "sha256:{{ terragrunt_shasum }}"

# - name: add terragrunt binary to path
#   become: true
#   copy:
#     src: /var/tmp/terraform-{{ terragrunt_version }}
#     dest: /usr/local/bin/terragrunt
#     mode: 0755

# - name: download helm tarball
#   become: true
#   get_url:
#     url: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
#     dest: /var/tmp/helm-{{ helm_version }}.tar.gz
#     checksum: "sha256:{{ helm_shasum }}"

# - name: untar helm
#   become: true
#   unarchive:
#     src: "/var/tmp/helm-{{ helm_version }}.tar.gz"
#     dest: "/var/tmp/"

# - name: add helm binary to path
#   become: true
#   copy:
#     src: /var/tmp/linux-amd64/helm
#     dest: /usr/local/bin/helm
#     mode: 0755
