- name: git alias st to status
  git_config: scope=global name=alias.st value=status

- name: git alias br to branch
  git_config: scope=global name=alias.br value=branch

- name: git alias co to checkout
  git_config: scope=global name=alias.co value=checkout

- name: install mavenlink bash aliases
  copy: dest=~/.bash-preferences.sh src=bash_preferences.sh

- name: load aliases
  lineinfile: dest=~/.bashrc line="source ~/.bash-preferences.sh"

- name: install tmux-conf to home
  copy: src=tmux-conf dest=~/.tmux.conf

- name: make vim default git editor because why the fuck should it be anything else
  shell: "git config --global core.editor 'vim'"

- name: does this have synaptics touchpad
  shell: "xinput list | grep Syn | awk '{ print $3,$4 }' | grep 'SynPS/2 Synaptics' >> /dev/null && echo $?"
  register: touchpad_enabled
  ignore_errors: true

- name: what is my touchpad id
  shell: xinput list | grep Syn | awk '{ print $6 }' | sed 's/^[^=]*=//'
  register: touchpad_id
  when: "{{ touchpad_enabled.stdout == '0' }}"

- name: turn off touchpad
  shell: xinput --disable "{{ touchpad_id.stdout }}"
  when: "{{ touchpad_enabled.stdout == '0' }}"

- name: install turn off trakcpad script
  become: true
  copy: dest=/usr/local/bin/turn-off-touchpad src=turn-off-touchpad.sh mode=0755
