---
- name: add docker apt key
  become: true
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id="58118E89F3A912897C070ADBF76221572C52609D"

- name: add docker apt repo
  become: true
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-xenial main" state=present

- name: install docker and dependencies
  become: true
  package: name={{ item }} state=latest  
  with_items:
    - docker-engine

- name: install docker-compose
  become: true
  pip: name="docker-compose" state="present"

- name: ensure docker group is present
  become: true
  group: name=docker state=present

- name: add user to docker group
  become: true
  user: append=yes user={{ lookup('env', 'USER') }} groups=docker

- name: ensure dot docker directory exists
  file: dest=~/.docker state=directory

- name: start docker daemon
  systemd: state=started enabled=yes name=docker
